---
dependency:
  name: galaxy

driver:
  name: podman

provisioner:
  name: ansible
  # log: true

verifier:
  name: ansible

scenario:
  name: oraclelinux-8

platforms:
  - name: oraclelinux-8
    image: oraclelinux:8