---
- name: Check if EPEL repository exist
  stat:
    path: "{{ epel_repo_file_path }}"
  register: epel_repo_file_path_result

- name: Import EPEL repository GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: >
    not epel_repo_file_path_result.stat.exists and
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS'
    ) and (
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )

- name: Install EPEL repository {{ansible_distribution}} {{ansible_distribution_major_version}}
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  retries: "{{ epel_global_downloads_retries }}"
  delay: "{{ epel_global_downloads_delay }}"
  register: result
  when: >
    not epel_repo_file_path_result.stat.exists and
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS'
    ) and (
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )

- name: Install EPEL package {{ansible_distribution}} {{ansible_distribution_major_version}}
  yum:
    name: "{{ epel_package }}"
    state: present
  retries: "{{ epel_global_downloads_retries }}"
  delay: "{{ epel_global_downloads_delay }}"
  when: >
    not epel_repo_file_path_result.stat.exists and
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'CentOS'
    ) and (
      ansible_distribution_major_version == '8' or
      ansible_distribution_major_version == '7' or
      ansible_distribution_major_version == '6'
    )

- name: Install extra packages {{ansible_distribution}} {{ansible_distribution_major_version}}
  dnf:
    name: "{{ epel_extra_packages }}"
    state: present
  retries: "{{ epel_global_downloads_retries }}"
  delay: "{{ epel_global_downloads_delay }}"
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'CentOS' and
    ansible_distribution_major_version == '8' and
    epel_enable_extras_repos

- name: Enable PowerTools repositories for {{ansible_distribution}} {{ansible_distribution_major_version}}
  command: dnf config-manager --set-enabled powertools
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'CentOS' and
    ansible_distribution_major_version == '8' and
    epel_enable_extras_repos
