---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  # log: true

verifier:
  name: ansible

scenario:
  name: centos-7

platforms:
  - name: centos-7
    image: centos:7
