---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  # log: true

verifier:
  name: ansible

scenario:
  name: docker

platforms:
  - name: redhat-8
    image: registry.access.redhat.com/ubi8/ubi

  - name: centos-8
    image: centos:8

  - name: redhat-7
    image: registry.access.redhat.com/ubi7/ubi

  - name: centos-7
    image: centos:7

  - name: centos-6
    image: centos:6

  - name: amazonlinux-2
    image: amazonlinux:2

  - name: amazonlinux-1
    image: amazonlinux:1
