---
dependency:
  name: galaxy

driver:
  name: podman

provisioner:
  name: ansible
  # log: true

verifier:
  name: ansible

scenario:
  name: amazonlinux-2

platforms:
  - name: amazonlinux-2
    image: amazonlinux:2
